# -*- coding: utf-8 -*-
"""Sales Forecasting Analysis System

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1przDGB8Ak5wqFeZo04rpI6PVC1ondnGf
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""# Load dataset"""

df = pd.read_csv("/content/sample_data/archive (4).zip")
print(df.head())
print(df.info())

"""# Data Cleaning & Preprocessing"""

print(df.isnull().sum())
df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True)
df = df.drop_duplicates()
df = df.ffill()

"""# Remove Unnecessary Columns"""

df = df.drop(columns=['ID', 'Metadata'], errors='ignore')

"""# Descriptive Statistics"""

print(df.describe())
total_sales = df['Sales'].sum()
print("Total Sales:", total_sales)
avg_sales = df['Sales'].mean()
print("Average Sales:", avg_sales)
print("Max Sales:", df['Sales'].max())
print("Min Sales:", df['Sales'].min())

"""# Sales Trend Analysis"""

plt.figure()
df.groupby('Order Date')['Sales'].sum().plot()
plt.title("Sales Trend Over Time")
plt.xlabel("Date")
plt.ylabel("Sales")
plt.show()

"""# Store / Product Analysis"""

store_sales = df.groupby('Region')['Sales'].sum()
print(store_sales)
store_sales.plot(kind='bar')
plt.title("Sales by Region")
plt.show()
product_sales = df.groupby('Category')['Sales'].sum()
print(product_sales)
product_sales.plot(kind='bar')
plt.title("Sales by Category")
plt.show()

"""# Time-Based Analysis"""

df['Year'] = df['Order Date'].dt.year
df['Month'] = df['Order Date'].dt.month
df['Day'] = df['Order Date'].dt.day
df.groupby('Month')['Sales'].sum().plot()
plt.title("Monthly Sales Trend")
plt.show()
df.groupby('Year')['Sales'].sum().plot(kind='bar')
plt.title("Yearly Sales")
plt.show()

"""# Relationship Analysis"""

plt.figure()
sns.heatmap(df.corr(numeric_only=True), annot=True)
plt.title("Correlation Heatmap")
plt.show()

"""# Histogram"""

plt.figure()
df['Sales'].hist()
plt.title("Sales Distribution")
plt.show()

"""# Box plot"""

plt.figure()
sns.boxplot(x=df['Sales'])
plt.title("Outlier Detection")
plt.show()

"""# Business Insights"""

print("Top Product:", product_sales.idxmax())
print("Lowest Product:", product_sales.idxmin())
print("Best Store:", store_sales.idxmax())

"""# Conclusion"""

print("EDA Completed Successfully!")